export let company_list = [
  "1 Tac",
  "1-800-Got-junk",
  "123inkjets",
  "123inkjets.com",
  "1800wheelchair.com",
  "1StopFlorists",
  "2xist",
  "310 Nutrition",
  "360training.com",
  "383 Media",
  "4InkJets",
  "525 America",
  "6 Pack Bags",
  "89th + Madison",
  "Absolute Software",
  "Account Name",
  "Ace Hardware",
  "Acer",
  "Adorama",
  "ADORNit",
  "AfricanMall",
  "AfterShokz",
  "Aidance",
  "Aidance Products",
  "Air Filters Delivered",
  "AirBnB UK",
  "Alibris",
  "Alloy Apparel",
  "AMC Network",
  "American Hemp Oil",
  "Amstar DMC",
  "Ananda Apothecary",
  "Annebuy",
  "Annke Security Inc",
  "Apollo Box",
  "Arhaus Furniture",
  "ArtistWorks",
  "Ashampoo GmbH &amp; Co",
  "Athentech Imaging Inc.",
  "Auslogics TweakBit",
  "Austin Canoe &amp; Kayak",
  "Auto Credit Express",
  "Auto Parts Warehouse",
  "Autodesk",
  "Automotive Manufacturing Group, Inc. (Recon)",
  "Automotix &amp; AutoPartsFair",
  "Automotix - AutoPartsFair",
  "Autoshack",
  "Autoshack CA",
  "Avast",
  "AVG Technologies",
  "Avid Technology , Inc.",
  "Avoya Travel",
  "Awishdeal",
  "B&amp;Q Plc (diy.com)",
  "Babeland/Good Vibes",
  "Babeth's Feast",
  "BabyOnlineDress",
  "Badandbold DE",
  "baggallini",
  "Bailey Hats",
  "BAKblade",
  "BannerBuzz",
  "Battlbox",
  "BCBG",
  "BCBGeneration",
  "beautystoredepot",
  "BEBE",
  "Begg Shoes",
  "Belkin - DE",
  "Belkin - UK",
  "Belkin US",
  "Belle Lily",
  "Bellesa Boutique",
  "Beretta",
  "Beretta USA Corp.",
  "Besame Cosmetics",
  "Best Cigar Prices",
  "Best of Signs",
  "BestVetCareUS",
  "Betteridge",
  "Billie Official",
  "Biogo Poland",
  "BioLief",
  "BizChair",
  "Bizuterua E Shop Poland",
  "Bluprint | Craftsy",
  "Bluum",
  "Body Spartan",
  "BoohooMan",
  "Boscov's Department Store Inc",
  "Box Office Ticket Sales",
  "Box Office Tickets",
  "Boys and Girls Club Denver Promo",
  "BrainMD Health",
  "Brilliance New York",
  "Brookstone",
  "Brother Canada",
  "Bugaboo",
  "Bulbhead",
  "BullGuard",
  "Burberry UK",
  "burnerapp.com",
  "Butcher Box",
  "BuyBest",
  "BuySeasons",
  "ByteMe",
  "Caesars Entertainment",
  "Cafe Joe",
  "Cakeflix",
  "California Psychics",
  "California Wine Club",
  "CALPAK",
  "Calzedonia",
  "Calzedonia Brazil",
  "Candy Club",
  "CanvasPop Inc",
  "Card Corp",
  "CARDCASH INC",
  "CarParts.com",
  "Carson Life",
  "Case-Mate",
  "Caseable",
  "Casio",
  "Caviar",
  "Cbazaar.com Inc",
  "CellSavers",
  "Cheap Flights Freak",
  "CheapFlightsNow",
  "Check Into Cash",
  "Chicwish",
  "Choice Home Warranty",
  "CHOiES",
  "Chow Sang Sang",
  "Chrome Battery",
  "Chrome Industries",
  "Chronicle Books",
  "Cigna",
  "CityPASS",
  "Clarivate",
  "Colorful Images",
  "Cosmetic Capital",
  "Cost Plus World Market",
  "Costume Supercenter",
  "Covers and All",
  "Craft Beer Club",
  "Credit Secrets",
  "Cricket Media",
  "Cricket Wireless LLC",
  "Cub Cadet",
  "Cub Coats",
  "cubcoats.com",
  "CuffLinks.com",
  "Current Catalog",
  "Davinci Vaporizers",
  "DAZN",
  "Decadent Minimalist",
  "Design Toscano",
  "Diesel",
  "Diet To Go",
  "Digital Media Solutions (formerly Fosina Marketing)",
  "Digital Media Solutions (Fosina Marketing)",
  "DMI Partners",
  "DMV Cheat Sheets",
  "Dolps",
  "Dorco",
  "Dragon Alliance LLC",
  "DriverFinderPro",
  "Dun &amp; Bradstreet",
  "dunninggolf.com",
  "eAccountable",
  "Early Moments, Sandvik",
  "eBillity",
  "Eckler's Automotive",
  "Eckler's Automotive (welcome signups)",
  "EdmondSoccerShop",
  "eHarmony",
  "ejuice.deals",
  "eluxury",
  "EM Cosmetics",
  "eManualOnline",
  "eManualOnline.com",
  "eMeals",
  "Engelmann Software",
  "EPC Media Inc",
  "Ethel M Chocolates",
  "Ettitude Inc",
  "Ever-Pretty",
  "Every Man Jack",
  "Everyday winner",
  "Everyman",
  "Ex Officio LLC",
  "Exposed Skincare",
  "Eyeconic",
  "EZ Lifestyle",
  "FairySeason",
  "Fandango",
  "Fascinating Diamonds",
  "FedEx",
  "Fendi",
  "Few Moda",
  "Find Your Trainer",
  "Fine Stationary",
  "Finejewelers",
  "Flatiron Media LLC",
  "Flex Watches",
  "FlexJobs",
  "FLIR Systems",
  "Flirty Aprons",
  "Flowercard Ltd",
  "Focallure",
  "Focus Camera",
  "FoodSaver (Newell Brands)",
  "Footjoy",
  "FootLocker",
  "Fosina Marketing",
  "Frecklebox",
  "FreeLotto",
  "Frey Inc",
  "Frost NYC",
  "Garmin",
  "Gatehouse Supplies",
  "GeardHardware",
  "Get Name Necklace",
  "Ghirardelli",
  "GhostBed",
  "GiftsForYouNow",
  "GiftTree LLC",
  "Gillett",
  "Girlfriend",
  "Glas Vapor",
  "GlasVapor",
  "Global Industrial (Systemax)",
  "Glow Concept",
  "Go Pup Socks",
  "GoGoalShop",
  "Gold Medal Wine Club",
  "Gold Urban",
  "Golf18 Network",
  "GolfLink",
  "Good Money",
  "Good Morning Snore Solution",
  "Goodyear",
  "Grassroots California",
  "Greatland",
  "Green Chef",
  "Green Dot",
  "Green Roads World",
  "Greg Norman Collection",
  "Grooming Lounge",
  "Groopdealz",
  "Growers House",
  "Gshock",
  "Gymshark Limited",
  "Hansen Surfboards",
  "Happy Socks",
  "Harperwilde",
  "Hawes &amp; Curtis Ltd - UK",
  "Healthy Back Institute",
  "HealthyWage",
  "Heat Holders",
  "Heathrow",
  "Heaven Gifts Inc. Ltd",
  "HempVana",
  "Herbspro/ Universal Herbs",
  "Herve Leger",
  "Hewlett Packard (HP) Canada",
  "Holy Clothing",
  "Home Defenders",
  "HomeAway",
  "HomeDNA",
  "Hopsy",
  "Hot Shot's Secret",
  "Hotel Travel Club",
  "Hotels.com",
  "Houzz, Inc",
  "HTC",
  "Hurleys UK",
  "Hurricane Golf",
  "I Can Read",
  "I Can Read (Digital Media Solutions)",
  "Ice Lolly",
  "iCommissions",
  "Identity Force",
  "IdentityForce",
  "IDM Computer Solutions Inc",
  "iLovesamples (Flatiron Media)",
  "In The Swim",
  "IncAuthority",
  "InfiniteAloe",
  "InkCartridges",
  "Inkkas",
  "Intimissimi",
  "IObit",
  "IP Vanish / OverPlay.Net",
  "IPAYLINKS LTD",
  "Iron Neck",
  "IRONMAN",
  "IRONMAN US",
  "ITeSHOP",
  "iZotope",
  "J&amp;P Cycles",
  "J.ING",
  "Jaanuu",
  "JAK ECIG",
  "Jared, The Galleria of Jewelry (Sterling Jewelers)",
  "Jared, The Galleria of Jewelry / Sterling Jewelers",
  "JavaPresse",
  "JC Whitney",
  "Jenson USA",
  "JensonUSA",
  "Joe's Jeans",
  "Johnston and Murphy",
  "Jora Credit",
  "JourneyEd.com",
  "JudaicaWebStore",
  "Juicy Couture",
  "June Jacobs",
  "Jurlique",
  "Kangol",
  "Kathmandu",
  "Kay Jewelers",
  "Kay Jewelers (Sterling Jewelers)",
  "Kayak LATAM",
  "KelbyOne LLC",
  "Kenneth Cole Productions LP",
  "Kidpik",
  "Kigurumi Shop",
  "KingKanine",
  "KitchenAid",
  "KitchenAid Canada",
  "Kneipp",
  "Knomo",
  "Koral",
  "Krol Majtek Pierwszy Poland",
  "Kuhl",
  "Kwanko",
  "Lab Testing API",
  "Laplink",
  "LaptopBatteryExpress.com",
  "Learn2Serve",
  "Legion GP",
  "Leisure Pro",
  "Lending Stream LLC",
  "Lenovo",
  "Lenovo - Belgium",
  "Lenovo - Denmark",
  "Lenovo - Finland",
  "Lenovo - FR",
  "Lenovo - Germany",
  "Lenovo - Italy",
  "Lenovo - Netherlands",
  "Lenovo - Norway",
  "Lenovo - Spain",
  "Lenovo - Sweden",
  "Lenovo - Switzerland",
  "Lenovo - UK",
  "Lenovo - US/MX/CO/BR",
  "Lenovo APAC",
  "Lenovo LAS",
  "Lett Clothing",
  "LexMod",
  "Lifeshield.com",
  "Liga Retro",
  "Lightake",
  "Lillian Vernon",
  "Linksys",
  "Loews Hotels Inc",
  "LOLE",
  "Loot Crate",
  "LovelyWholesale",
  "Lowe's Companies",
  "Lumen5",
  "Lysse",
  "Manduka LLC",
  "Maps.com",
  "Marc Jacobs",
  "Mario Badescu",
  "Marmot",
  "MASC by Jeff Chastain",
  "Master Debonair",
  "Master Events",
  "Master Matchmakers",
  "MasterPan",
  "Maytag Corp",
  "McAfee Direct",
  "McAfee eBiz",
  "McAfee US/CA",
  "MDM Exclusives (Flatiron Media)",
  "Medifast",
  "MedjetAssist",
  "Melidress",
  "Mens Italy",
  "Mens USA",
  "Merchant Account Solutions (2017)",
  "Mobile Maniacos",
  "MobileHelp",
  "ModCloth",
  "Modern Bathroom",
  "Modsy",
  "Molr Dental Club",
  "Moneygram",
  "Mono Price",
  "Monster Store",
  "Morris 4x4 Center",
  "Motorola Inc",
  "MRP",
  "MTD",
  "My Sensual Secrets",
  "N8 Essentials",
  "n:Philanthropy",
  "National Underwriter",
  "Nations Info",
  "Naturally Serious",
  "Neat",
  "Neato Robotics",
  "nero",
  "Net 10 Wireless",
  "Neuxpower",
  "NewAir",
  "NewFrog",
  "NewFrog &amp; CesDeals",
  "Next Big Idea Club",
  "Next UK",
  "Nfstrike",
  "Nice Kicks",
  "Nicole Miller",
  "Nina Shoes",
  "Nixon",
  "nixplay",
  "Nolo",
  "Nourage",
  "Nuheara",
  "Nurse Next Door",
  "Nurx",
  "NutraClick / Hungry Fish",
  "NVIDIA",
  "OakStone",
  "Oakstone Publishing, LLC",
  "Office Designs",
  "Office Furniture 2 Go",
  "Oliso Inc",
  "Omaze Dream House",
  "Omaze LLC",
  "OMRON",
  "Onthebeach.co.uk",
  "OPKIX",
  "Our Campus Market",
  "Our Campus Market (OCM)",
  "Outdoor Technology",
  "Ozone Design (Ozone Socks)",
  "Pacific Holidays",
  "Pagoda",
  "Paige Denim",
  "Palace Resorts",
  "Palm Beach Jewelry",
  "Panda Security",
  "Paqueta Esportes",
  "Park 'N Fly",
  "Park Holidays",
  "PBS",
  "PCM",
  "PCM - Tiger Direct CA",
  "Peet's Coffee &amp; Tea",
  "PeggyBuy",
  "PeggyBuy (DIYHomeDeals)",
  "Peoples Jewellers",
  "Peoples Jewellers (Sterling Jewelers)",
  "Perfect Memorials",
  "Perfect Origins",
  "Permanent Test Account",
  "Personal Trainer Food LLC",
  "Persun.fr",
  "Pet Mountain",
  "Petals Network",
  "Petcare Supplies",
  "Peter Thomas Roth",
  "Petplan",
  "Pharmapacks",
  "Philosophy",
  "Piercing Pagoda (Sterling Jewelers)",
  "Pimsleur Language",
  "Pina Court",
  "Piriform",
  "Plant Therapy",
  "Plantronics Inc",
  "PlayOn",
  "Plusinlove",
  "Polarn O. Pyret",
  "Polynesia",
  "Post Mates",
  "Precious Moments",
  "PrimeParty",
  "Psychic Source",
  "Puls (formerly CellSavers)",
  "Pure Hemp Botanicals",
  "Pure Talk USA",
  "Purereliefe.com",
  "Puritan's Pride",
  "Puritans Pride",
  "Purple Carrot",
  "Quest 4 Toner",
  "quickship.com Inc",
  "Quit Stop Now",
  "Raidlight",
  "Rapala Corporation",
  "Ravean",
  "Raw Generation",
  "Razer",
  "RealHer",
  "RebDolls",
  "Reebok",
  "RegistryFinder",
  "Reptile City",
  "RestaurantFurniture4Less",
  "Rite Aid",
  "Roadie Tuner",
  "Rock 'n' Roll Marathon",
  "Rodial",
  "Rojo’s Famous",
  "Rokform",
  "Rossignol Ski Co Inc",
  "Rush49",
  "Ryderwear",
  "Sabon NYC",
  "Sam Ash Music",
  "Sam's Club",
  "Samko and Miko Toy Warehouse",
  "Samsung",
  "Samsung UK",
  "Save The Children",
  "Sebastian Cruz Couture",
  "Second Skin Audio LLC",
  "SelfLender",
  "SemaLife",
  "Sheet Music Plus",
  "Shefit",
  "Shelving",
  "Shipt Inc",
  "Shmoop",
  "Shoe Carnival",
  "Shoe Palace",
  "Shoplet",
  "Shutterstock Inc",
  "Sideshow Collectibles",
  "Simon Sez IT",
  "Simple Mobile LLC",
  "Simpli Home",
  "Six Pack Bags",
  "SketchBox",
  "SmallRig",
  "Smithsonian",
  "SoccerDealShop",
  "Social Civilian",
  "SocialEras",
  "Soda PDF",
  "Sootheen",
  "Soufeel",
  "SOUFEEL",
  "South Beach",
  "Southern Kitchen",
  "SpareFoot Inc",
  "Special Olympics Washington Raffle",
  "Speck Products",
  "Sphynx",
  "Spiral Direct",
  "SpoofCard",
  "Sports Crate",
  "Sports Interaction",
  "Springboard",
  "Stackpath (formerly Highwinds)",
  "Start-rite Shoes Ltd",
  "Station Casinos LLC",
  "Sterling Jewelers",
  "Stila Corp",
  "Straight Talk",
  "Strong VPN affiliate network",
  "StrongVPN",
  "Succulent Studios",
  "Suggar",
  "Suggesty",
  "SuitedConnector",
  "Sundance Now",
  "Sunny Sports",
  "SuperStar",
  "Swanson Health",
  "SysTools Software Pvt. Ltd.",
  "Talever",
  "Talkspace",
  "Targus Inc.",
  "Tatbrow",
  "Taylor Made Golf Co Inc",
  "Teleflora",
  "Telestream",
  "Tessabit",
  "Test",
  "Test Account",
  "Test Jun",
  "TFC marketing/purereliefe.com",
  "The Blooom Inc.",
  "The Economist",
  "The Finish Line , Inc.",
  "The Gld Shop",
  "The Gold Gods",
  "The Hat Company",
  "The House of Staunton",
  "The iOutlet",
  "The Mountain",
  "the mountain",
  "The Perfect Rug",
  "The Proactiv Company LLC",
  "The Purple Carrot",
  "The Shelving Store",
  "The Supplies Shop",
  "Thrive Market",
  "TicketNetwork Inc.",
  "Tidal",
  "TigerDirect , Inc.",
  "Tire Buyer",
  "TollFreeForwarding.com",
  "Total Defense",
  "Total Wine &amp; More",
  "Total Wireless",
  "Touchstone Essentials Foundation",
  "Tracfone",
  "TracFone Wireless",
  "TrackR",
  "Trails.com",
  "Trend Micro APAC",
  "TrendMicro EMEA",
  "TrendMicro US",
  "Trendy Butler",
  "Tropical Oasis",
  "Troy-Bilt",
  "TruGreen",
  "Trupanion",
  "Tulo",
  "Tushy",
  "Twelve South",
  "U.S. Elite",
  "UK Soccer Shop",
  "Ultimate Vape Deals",
  "Unagi Scooters",
  "Unbeatable Sale",
  "Under Armour",
  "UnionBay",
  "Uniwigs",
  "UpSellit",
  "Urban Decay Canada",
  "UrbaneBox",
  "US Chess Federation Sales",
  "valiant vapes",
  "Veoveo Poland",
  "Versed",
  "Vilacto",
  "Villeroy &amp; Boch",
  "Vineyard Vines LLC",
  "Virtue Labs",
  "VitalSource",
  "Voce (BR)",
  "Voidu",
  "VSP Direct",
  "Wave Soda",
  "Way.com",
  "We Do Logos (Brazil)",
  "WebEyeCare.com",
  "Western Digital US",
  "WhatsMode",
  "Whirlpool Corporation",
  "Whirlpool Inside Pass",
  "Whistle Labs, Inc",
  "Wholesale Chess",
  "Wicked Good CupCakes",
  "Wig Encounters",
  "Wildfox",
  "Wing Girl Method",
  "WonderPedic",
  "Worldwide Brands",
  "WorldWide Golf",
  "Wyndham Hotels",
  "Xero Shoes",
  "Xm Radio Inc",
  "Yaasa Studios",
  "YeahBra",
  "YI Technology",
  "Yogi Surprise",
  "Yummi Life",
  "Yummie",
  "Z-Sleep",
  "Zales",
  "Zbest",
  "ZEN Rooms",
  "ZoneAlarm by CheckPoint",
  "Zoro UK (Cromwell)",
];